### ISSUE TITLE
requirement.ext problem

### ISSUE THREAD

**Issue by BillyXYB** [yashkant/spad#1]
Hi, the requirement.txt has -e git+ssh://git@github.com/yashkant/spad-code.git@06bfb465ff0cf50f86da8a2ed35b46983255b4ac#egg=latent_diffusion", which is not accessible. 

I'd be appreciated if you could look into that!
Thanks for the cool project.

**Comment by yashkant** [comment]
thanks, will fix!

**Comment by yashkant** [comment]
please try again, should be fixed now.

**Comment by BillyXYB** [comment]
For me, it works by installing the PyTorch, torch vision etc that is most compatible with xformer, then use the rest of documentation .
