### ISSUE TITLE
Evaluation setup

### ISSUE THREAD

**Issue by jh27kim** [yashkant/spad#11]
Hi thanks for releasing SPAD model. 

I just have few questions regarding the evaluation. 

In the paper FID is reported but does not seem to mention how the reference set images are constructed. 
Also I could not find the 1,000 text prompts used for evaluation (text-to-MV).

Could you please share the details on the text-to-MV experiment?

Thanks

**Comment by yashkant** [comment]
hi @jh27kim, 

thanks for checking out spad. 

if i remember correctly, i randomly sampled a subset of ~1000 images from objaverse renders for FID computation. 

for text-to-multiview evaluation, i similarly sampled a subset of 1000 captions from objaverse, i have pasted the list here: https://gist.github.com/yashkant/1af9553f86da10ea32ec78ba6f2014f6

additionally, if you are looking for prompts used for text-to-3d experiments those are available here: https://gist.github.com/yashkant/3c24943a768b79513e1cb9cfaf78c842

good luck!
