### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by Tzy010822** [yashkant/spad#2]
<img width="779" alt="image" src="https://github.com/yashkant/spad/assets/112625011/1bcfdb25-4dc1-4716-bbf6-7caaaea5b654">

**Comment by Tzy010822** [comment]
It seems solved when https://github.com/yashkant/spad/blob/4c9aa181758f1dc2927221eda45ebfe93cf0cc42/scripts/inference.py#L159 changes to >=.

**Comment by yashkant** [comment]
fixed, thanks!
