### ISSUE TITLE
Image-conditioned Novel View Synthesis

### ISSUE THREAD

**Issue by StepInfinite** [yashkant/spad#8]
Dear authors, thanks for the nice work.

As the paper claimed, SPAD supports both text-conditioned Novel View Synthesis and single view image Novel View Synthesis.
I have read the READ.ME and source code carefully , but only find the inference code with text caption condition. Thus I want to check that whther you intend to release the inference code for Image-conditioned novel view synthesis.

Looking forward to your response!

Best

**Comment by yashkant** [comment]
hi, thanks for your interest.  unfortunately, we won't be releasing the image-conditioned NVS models. 

one possible workaround:

i think it is possible to pass the input image to one the multi-view branches of SPAD during inference and freeze it (push in noised input image, and dont use the denoising output). 

this is similar to how we trained the image-to-views (NVS) model in the paper, although i am unsure if it would generalize?
